version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./nginx.dockerfile
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/log/:/var/log/nginx/"
    ports: 
      - 80:80
      - 443:443
    restart: always
    networks: 
      - spring_app_net
    depends_on: 
      - spring_app
    # command: nginx -g daemon off;

  mysql_db:
    build:
      context: ./mysql
      dockerfile: ./mysql.dockerfile
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: myapp
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql/myapp/:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - spring_app_net
    cap_add:
      - SYS_NICE

  spring_app:
    build:
      context: ./myapp
      dockerfile: ./myapp.dockerfile
    container_name: spring_app
    expose: 
      - 8080
    # ports:
    #   - 8080:8080
    depends_on:
      - mysql_db
    # restart: on-failure
    restart: always
    networks: 
      - spring_app_net
    command: ./gradlew bootRun

networks: 
    spring_app_net: